### ISSUE TITLE
Google Play: Device and Network Abuse policy violation

### ISSUE THREAD

**Issue by megaacheyounes** [Explore-In-HMS/huawei.ads.applovin_mediation#4]
version 13.4.61.302 of this adapter violates Google Play Store policy, below is email received from google when attempting to release the app: 
![apploving_adapter_playstore_issue](https://github.com/Explore-In-HMS/huawei.ads.applovin_mediation/assets/36759976/de1685df-5586-4bad-85a2-cd192d42ac26)

**Comment by linean** [comment]
I can provide an update on this situation. I collaborated with Huawei in an attempt to address this problem for another application, but unfortunately, we were unable to find a solution. As a result, we had to remove the SDK from the application, which is disappointing. 😞
